# Generated by Django 5.2.6 on 2025-09-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidences/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajo_aplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='application_jobs.applicationjobmodel')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
    ]
