# Generated by Django 5.2.6 on 2025-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_companies', models.IntegerField(default=0)),
                ('total_vacancies', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('total_accepted_applications', models.IntegerField(default=0)),
                ('total_rejected_applications', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistics',
            },
        ),
    ]
