# Generated by Django 5.2.6 on 2025-09-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_estudiantemodel_user_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationJobModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_jobs', to='students.estudiantemodel')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_jobs', to='vacancies.vacancy')),
            ],
            options={
                'db_table': 'application_jobs',
                'unique_together': {('estudiante', 'vacante')},
            },
        ),
    ]
